---
name: CI

env:
  ROLE_NAME: wcm_io_devops.jenkins_plugins

defaults:
  run:
    working-directory: 'wcm_io_devops.jenkins_plugins'

'on':
  pull_request:
  push:
    branches:
      - master
      - "feature/migrate-to-github-actions"

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ANSIBLE_VERSION: 2.7.*
            ANSIBLE_LINT_VERSION: 4.2.*
          - ANSIBLE_VERSION: latest

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: '${{ env.ROLE_NAME }}'

      - name: Cache PIP
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install role requirements
        uses: BSFishy/pip-action@v1
        with:
          requirements: "${{ env.ROLE_NAME }}/requirements.txt"

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install yamllint ansible-lint

      - name: Create ansible.cfg
        run: "printf '[defaults]\nroles_path=./tests/requirements/:../' > ansible.cfg"

      - name: Lint code.
        run: |
          ls -la
          pwd
          yamllint .
          ansible-lint
